projects/loader_circle/index.css
projects/loader_circle/index.html
projects/loader_circle_dots/index.css
projects/loader_circle_dots/index.html

Sahil1966 issue 2

---

projects/loader_circle/index.css
projects/loader_circle/index.html
projects/loader_circle_dots/index.css
projects/loader_circle_dots/index.html
projects/loader_double_circle/index.css
projects/loader_double_circle/index.html

Sahil1966 issue 3

---

projects/double_loader/index.css
projects/double_loader/index.html
projects/loader_circle/index.css
projects/loader_circle/index.html
projects/loader_circle_dots/index.css
projects/loader_circle_dots/index.html
projects/loader_double_circle/index.css
projects/loader_double_circle/index.html

Sahil1966 issue 4

---

projects/bar-loader/index.css
projects/bar-loader/index.html

Added bar loader
**Checklist:**

Added bar loader

---

projects/slider-loader/index.css
projects/slider-loader/index.html

Added slider loader
**Checklist:**

Added slider loader

---

projects/progress-loader/index.css
projects/progress-loader/index.html

Added progress loader
**Checklist:**

Added progress loader

---

projects/wave-loader/index.css
projects/wave-loader/index.html

Added wave loader
**Checklist:**

Added wave loader

---

projects/dice-loader/index.css
projects/dice-loader/index.html

Added dice loader
**Checklist:**

Added dice loader

---

projects/3d-layer-loader/index.css
projects/3d-layer-loader/index.html

Added 3d loader
**Checklist:**

Added 3d loader

---

projects/triangle_loaders/index.css
projects/triangle_loaders/index.html

Added Traingle loader
**Checklist:**

added triangle loader

---

projects/3dotLoader/index.css
projects/3dotLoader/index.html

Added new loader
Added 3dotLoader
**Checklist:**

Added 3 dots loader

---

projects/tennis-loader/index.css
projects/tennis-loader/index.html

added tennis-loader

---

projects/2dotloaders/index.css
projects/2dotloaders/index.html

added 2dotloaders
added html and css
**Checklist:**

added html,css

---

projects/multiColor_Curve_Loader/index.html
projects/multiColor_Curve_Loader/style.css

I have made a multi-color loader which is circular and litlle curvy.
- [✓] My code follows the style guidelines of this project
- [✓] I have performed a self-review of my own code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] I have made corresponding changes to the documentation
- [✓] My changes generate no new warnings

MultiColor Curve loader

---

projects/Heart-Shape-Preloader/index.html
projects/Heart-Shape-Preloader/style.css
projects/kinetic-loader/README.md
projects/kinetic-loader/index.html
projects/kinetic-loader/style.css

- [✓] My code follows the style guidelines of this project
- [✓] I have performed a self-review of my own code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] I have made corresponding changes to the documentation
- [✓] My changes generate no new warnings

Heart Shape preloader

---

projects/atom/atom.css
projects/atom/atom.html
projects/dottedLoader/dottedLoader.css
projects/dottedLoader/dottedLoader.html
projects/loveLoader/loveLoader.css
projects/loveLoader/loveLoader.html
projects/tubeLoader/tubeLoader.css
projects/tubeLoader/tubeLoader.html

added the tubeLoader

---

projects/atom/atom.css
projects/atom/atom.html
projects/dottedLoader/dottedLoader.css
projects/dottedLoader/dottedLoader.html
projects/loveLoader/loveLoader.css
projects/loveLoader/loveLoader.html
projects/tubeLoader/tubeLoader.css
projects/tubeLoader/tubeLoader.html

**Checklist:**
- [XI have commented my code, particularly in hard-to-understand areas

added atom loader

---

projects/atom/atom.css
projects/atom/atom.html
projects/dottedLoader/dottedLoader.css
projects/dottedLoader/dottedLoader.html

Saichidvi1

---

projects/atom/atom.css
projects/atom/atom.html
projects/dottedLoader/dottedLoader.css
projects/dottedLoader/dottedLoader.html
projects/loveLoader/loveLoader.css
projects/loveLoader/loveLoader.html

added the loveLoader

---

projects/double-filled loader/index.html
projects/double-filled loader/style.css

NIL
Double-filled loader added
New loader added
**Checklist:**
NULL

double filled loader added 🚀

---

projects/spin-loader/index.css
projects/spin-loader/index.html

Added spin loader
**Checklist:**

added spin-loader

---

projects/spin-loader/index.css
projects/spin-loader/index.html
projects/spiral-loader/index.css
projects/spiral-loader/index.html

Added spiral loader
**Checklist:**

Spiral loader

---

projects/blink-loader/index.css
projects/blink-loader/index.html
projects/dot-loader/index.css
projects/dot-loader/index.html

**Added dot loader**
**Checklist:**

added dot loader

---

projects/ben10-watch-loader/index.css
projects/ben10-watch-loader/index.html

**Issue reference:*add css loader*
**Checklist:**

added loader

---

projects/honey-comb-loader/index.html
projects/honey-comb-loader/style.css

No issue is referenced.
New **Honey Comb** Loader added.
A new loading effect was added.
**Checklist:**
No additional information is needed.

honey_comb_loader added 🎉

---

projects/Microsoft-loader/index.html
projects/Microsoft-loader/style.css

No issue referenced
Microsoft loader added.
New loader added.
**Checklist:**
No additional information.

microsoft loader added ✔

---

projects/pencil-loader/index.css
projects/pencil-loader/index.html

added pencil-loader
added html, css files
**Checklist:**

added pencil-loader

---

index.html
style.css

no reference
mosiac loader added
new loader added
**Checklist:**
no additional information needed.

mosiac-loader added ✅

---

projects/zoomloader/index.css
projects/zoomloader/index.html

added Zoom in/out loader
added index.js & index.css
**Checklist:**

added zoomloader

---

projects/quarter-loader/index.css
projects/quarter-loader/index.html

Added HTML, CSS
Added quarter loader.
**Checklist:**

Added quarter loader

---

index.css
index.html

Added HTML , CSS
Added 4 circle loader
**Checklist:**

Added 4circle loader

---

projects/pulsing-loader/index.html
projects/pulsing-loader/style.css

Added HTML,CSS
Added pulsing loader
**Checklist:**

Added pulsing loader

---

projects/loader/indexx.html
projects/loader/style.css

Added HTML,css files
Added Umbrella loader
**Checklist:**

Added loader files

---

projects/loading loader/index.html
projects/loading loader/style.css

- add loading loader
**Checklist:**

add loading loader

---

projects/bulge loader/index.html
projects/bulge loader/style.css

- Add bulge loader
**Checklist:**

Add bulge loader

---

projects/flat loader/index.html

- Add flat loading
**Checklist:**

Add flat loading

---

projects/Windows loader/index.html

- Add windows loader
**Checklist:**

Add windows loader

---

projects/Space-loader/index.html
projects/Space-loader/style.css

**Issue reference:** 
no issue reference
edit html css files
edit Space loader
**Checklist:**

added files

---

projects/progressloader/index.html
projects/progressloader/style.css

progress loader added
index.html && style.css added
**Checklist:**

progress loader added

---

projects/pac-man_loader/index.html
projects/pac-man_loader/style.css

no issue 
added pac man loader using css and html
added css and html
**Checklist:**

1st commit for pac-man-loader

---

projects/Cube-Drop-Loader/index.html
projects/Cube-Drop-Loader/style.css

No issue referred.
Cube loader added.
new files added.
**Checklist:**
No information

cube_drop_loader added

---

projects/clockloader/index.css
projects/clockloader/index.html

Clock loader added
index.html & index.css added
**Checklist:**

clock_loader added

---

arrow-loader/index.html
arrow-loader/style.css

Added arrow loader
Added html and css
**Checklist:**

Added arrow loader

---

projects/circular_loader/index.css
projects/circular_loader/index.html

circular loader
